version: '3'

services:
  ezxssdb:
    container_name: ezxssdb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - ./ezxssdb:/var/lib/mysql
  ezxss:
    build: ./php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - ezxssdb
